### PR TITLE
Vendor dependencies.

### PR DESCRIPTION
**Pull request by kisom**
This runs [godep](https://github.com/tools/godep) on the repository.

### CODE REVIEW

**Comment by lziest** [comment]
thank you @jacobhaven

**Comment by grittygrease** [comment]
It might make sense to use the Go 1.5 vendor experiment here: https://medium.com/@freeformz/go-1-5-s-vendor-experiment-fd3e830f52c3 cc: @jkroll

**Comment by jacobhaven** [comment]
I've updated this PR to use `GO15VENDOREXPERIMENT`

**Comment by jacobhaven** [comment]
Build is failing because `cloudflare/go-metrics/influxdb` has an 2-year old obsolete import path. This should fix it: https://github.com/cloudflare/go-metrics/pull/1/files

**Comment by jacobhaven** [comment]
We don't seem to be able to build the CGO at `github.com/google/certificate-transparency/go/merkletree`

**Comment by jacobhaven** [comment]
I've added an OSX build to the Travis CI config and updated the certificate-transparency dependency and transport package's `root_cgo_darwin.go` (in #414) to pass CI tests on linux and osx

**Comment by jacobhaven** [comment]
`test.sh` uses `xargs` in a way incompatible with both Linux and OSX, so we need to update that. Otherwise, all the tests with vendored dependencies pass on both platforms.

**Comment by jacobhaven** [comment]
Alright, everything should be up-to-date here. In the future, godep will need to be used to update any new dependencies (Travis will immediately fail otherwise)

**Comment by kisom** [comment]
LGTM.

**Pull request merged**
