### PR TITLE
Upgrade TLS1.2 to TLS1.3

### PR DESCRIPTION
**Pull request by lbarman**
Hello, this is a work in progress which aims at upgrading the TLS version to 1.3 in the scan functionality. This follows issue https://github.com/cloudflare/cfssl/issues/1089.

I'll update this PR with the relevant info as I progress. Comments along the way are welcome !

This superseeds https://github.com/cloudflare/cfssl/pull/1098

### Warning

This PR updates **replaces** the current TLS1.2 implementation with the TLS1.3 implementation from Go 1.13.9. It is enabled by default.

It adds the following modules:
- golang.org/x/crypto/hkdf
- golang.org/x/crypto/curve25519
- golang.org/x/crypto/chacha20poly1305

## Roadmap

My goal: `cfssl scan -family TLSHandshake google.com` works and uses TLS1.3 instead of 1.2

## Status

`cfssl scan -family TLSSession google.com`:
a

TODOs:
- [ ] Fix tests (that were coded for TLS1.2) and make sure they pass
- [x] Upgrade `cfsslscan` to work with the interface of TLS1.3 (slightly different than 1.2)
- [ ] Upgrade the Grading algorithms to use/reflect TLS1.3, which includes:
- [ ] Scanning with both TLS1.2 and TLS1.3
- [ ] Rewiring some version-specific checks (e.g., SessionResumption in 1.2) to be done only with their version

## Questions / Decisions to be made
Add a CLI option to explicitly scan in 1.2 or 1.3 ?

### CODE REVIEW

**Comment by claucece** [comment]
Hi, @lbarman ! I'll probably will start working on these tasks to finish this PR.. is it ok with you?

**Comment by lbarman** [comment]
Hey @claucece, absolutely! thanks :)

**Comment by claucece** [comment]
This is now superseded by: https://github.com/cloudflare/cfssl/pull/1120

@lbarman , small question, why do you change to use `x/crypto/ed25519` and `x/crypto/chacha20poly1305`

**Comment by claucece** [comment]
@lbarman I see why is needed now: because of go 1.12

**Pull request closed without merging**
