### PR TITLE
use slot ids in the cfssl pkcs11 api

### PR DESCRIPTION
**Pull request by jmhodges**
It was using TokenLabels solely to select slots but those can have duplicates on the same HSM. Instead, use slot IDs with them.

Found in https://github.com/letsencrypt/boulder/pull/784

### CODE REVIEW

**Comment by jmhodges** [comment]
This is an API break, but a required one.

**Comment by jmhodges** [comment]
Argh, sorry. I thought this patch had already been tested against your codebase instead of just ours.

Fixing.

**Comment by kisom** [comment]
I think this will address #259, also.

**Comment by jmhodges** [comment]
Okay, that test failure seems to be an artifact of the travis config.

Specially, since my code is coming from jmhodges/cfssl, instead of cloudflare/cfssl, the `go get  github.com/cloudflare/cfssl/...` can't work correctly.

**Comment by jmhodges** [comment]
If someone could push my branch into the cloudflare version of this and check the build, that would be a great kindness.

**Comment by kisom** [comment]
@jmhodges Pushed.

**Comment by jmhodges** [comment]
The build error remains but I cannot reproduce it by running the tests locally with `go test ./...` in the cfssl repo.

**Comment by jmhodges** [comment]
Ah, ha. I got repro with a `go install`. Okay.

Thank you for the help.

**Pull request closed without merging**
