### PR TITLE
Upgrade to zlint 2.1.0.

### PR DESCRIPTION
**Pull request by jsha**

### CODE REVIEW

**Comment by cpu** [comment]
@jsha FYI: I think you accidentally included a few test-generated resources (_that should probably be in the project `.gitignore`_) in your branch: `certdb/testdb/certstore_development.db` and `ocsp/testdata/sqlite_test.db`.

**Comment by jsha** [comment]
Now the error is:

```
    bundle_from_file_test.go:346: expected no error. but an error occurred: {"code":1211,"message":"x509: certificate has expired or is not yet valid"}
```

Will check it out.

**Comment by cpu** [comment]
> Will check it out.

I was curious and did a little bit of leg-work here. tl;dr, it's a problem with master: https://github.com/cloudflare/cfssl/issues/1110

**Comment by jsha** [comment]
Hi Cloudflare team,

We'd love to get this PR merged when you get a chance so we can upstream it in Boulder.

Thanks,
Jacob

**Comment by nickysemenza** [comment]
Sorry no one took a look at this - I realize the tests are just failing because this branch needed to be rebased to include changes in #1111 (thanks for that!), but #1137 just popped up on my feed so I think it makes sense to leapfrog to the latest version of zlint.

**Comment by jsha** [comment]
Sounds good! Closing this.

**Pull request closed without merging**
