### PR TITLE
Add support for "Standard" AuthKey loaded from environment variable or file

### PR DESCRIPTION
**Pull request by jacobhaven**

### CODE REVIEW

**Comment by kisom** [comment]
LGTM.

**Comment by bkleef** [comment]
@kisom @jacobhaven how to use this functionality? Looks very useful to us!

**Comment by bkleef** [comment]
OK it can be used by:

```
{
  "signing": {
    "default": {
      "auth_remote":{
          "auth_key": "sample",
          "remote": "localhost"
        }
    }
  },
  "auth_keys": {
    "sample": {
      "type":"standard",
      "key":"env:CFSSL_KEY"
    }
  },
  "remotes": {
    "localhost": "https://127.0.0.1:8888"
  }
}
```

**Comment by leanderjanssen** [comment]
When trying to load the key from a file, I get the following error:
```
2017/05/25 08:03:57 [DEBUG] loading configuration file from config.json
2017/05/25 08:03:57 [DEBUG] parse expiry in profile
2017/05/25 08:03:57 [DEBUG] expiry is valid
2017/05/25 08:03:57 [DEBUG] match auth key in profile to auth_keys section
2017/05/25 08:03:57 [DEBUG] failed to create new standard auth provider: encoding/hex: odd length hex string
Failed to load config file: {"code":5200,"message":"failed to create new standard auth provider"}
```

I'm using the following auth_keys section in my config.json:
```
  "auth_keys": {
    "base": {
      "key": "file:base.key",
      "type": "standard"
    }
  }
```

The base.key contains something like:
`4ee4e09eb513aafe68ccce0d3867476a`

**Comment by leanderjanssen** [comment]
I've fixed my own issue here.
It was as simple as making sure there is no newline character at the end of the string.

For example, by generating it using openssl and stripping the newline character:

`echo -n $(openssl rand -hex 16 | tr -d '\n') > base.key`

**Pull request merged**
