### PR TITLE
Allow specifying/overriding OCSP validity period

### PR DESCRIPTION
**Pull request by rolandshoemaker**
Allows for backdating OCSP responses which is something we've wanted to do in [letsencrypt/boulder](https://github.com/letsencrypt/boulder) for a while.

Adds a test that validates this doesn't break current usage and tests the new behavior.

### CODE REVIEW

**Comment by lziest** [comment]
lgtm, wait on build

**Comment by rolandshoemaker** [comment]
OSX build appears unhappy, not entirely sure why.

**Comment by lziest** [comment]
we use a staticcheck lib which usually took around 30 minutes to finish. So it will get shut down for no output for 30 minutes.

**Comment by lziest** [comment]
yolo mac build.

**Pull request merged**
