### PR TITLE
deps: update /x/crypto, fix Go 1.13 test breakage.

### PR DESCRIPTION
**Pull request by cpu**
When using modern `golang.org/x/crypto/ed25519` on Go 1.13 the `x` library is a small wrapper around the stdlib version. In this case the CFSSL `derhelper` `ParsePrivateKeyDER` function needs to match on the stdlib type.

To maintain backwards compat with Go 1.12 the helper code is split by a build tag. The legacy code can use the `golang.org/x/crypto/ed25519` import while the new Go 1.13+ code can use the `crypto/ed25519` import.

Build tags and code duplication are ugly but I couldn't think of another solution that wouldn't require dropping Go 1.12.x support.

### CODE REVIEW

**Comment by jsha** [comment]
FYI it looks like Travis tests passed even though the GitHub UI is still showing the yellow "pending" icon.

**Comment by cpu** [comment]
:wave: @cbroglie @mihirjham @lgarofalo hi folks. Do you think you'll be able to give this PR (and #1080) a once over in the next week or two? My employment situation changed from the time I opened these PRs and it would be nice to get them wrapped up to unblock Let's Encrypt from updating their ZLint dependency. If you don't think you'll have cycles that's OK but I'll probably hand these PRs off to someone else in that event.

Thanks!

**Comment by claucece** [comment]
Hi, @cpu!

Thanks so much for this!

The only problem I see with this is that it will start failing for go.1.14, as it only checks for anything that is !go.1.13. Have you tested it with go1.14?

Something that can also be done is to provide an appropriate error message when the build fails for a given version. Another thing that can be done is to use go contraints (https://medium.com/@theckman/version-constraints-and-go-c9309be15773).. will you be interested into looking into that?

I can also change the code to match that pattern, so let me know ;)

Thanks!

**Comment by cpu** [comment]
Hi @claucece, thanks for the reply!

> The only problem I see with this is that it will start failing for go.1.14, as it only checks for anything that is !go.1.13. Have you tested it with go1.14?

Good point. I'll test this with Go 1.14. I'm not familiar enough with build tags to know for sure what the outcome will be. I _thought_ that `!go 1.13` and `go 1.13` meant "less than Go 1.13" and "Go 1.13 and higher" but could be mistaken.

> Something that can also be done is to provide an appropriate error message when the build fails for a given version. Another thing that can be done is to use go contraints

I think adding another dependency might be overkill for this case. I'll see what I can come up with based on vanilla build tags and we can go from there. Sounds good?

Thanks!

**Comment by cpu** [comment]
Hi again @claucece :wave:

> The only problem I see with this is that it will start failing for go.1.14, as it only checks for anything that is !go.1.13. Have you tested it with go1.14?

I verified the fix continues to work on Go 1.14:

```bash
~/go/src/github.com/cloudflare/cfssl$ go version
go version go1.14 linux/amd64

~/go/src/github.com/cloudflare/cfssl$ git rev-parse HEAD
81e54732c78bc0320d4f6061b9d27b441d8ff8f7

~/go/src/github.com/cloudflare/cfssl$ go test -count=1 --test.run TestParsePrivateKeyPEM ./helpers/...
ok  	github.com/cloudflare/cfssl/helpers	0.004s
ok  	github.com/cloudflare/cfssl/helpers/derhelpers	0.005s [no tests to run]
ok  	github.com/cloudflare/cfssl/helpers/testsuite	0.006s [no tests to run]
```

I ran the specific test I fixed in this branch with `--test.run` because there are other tests that are broken with Go 1.14. E.g. the case you ran into described in https://github.com/cloudflare/cfssl/issues/1076 (and another in https://github.com/cloudflare/cfssl/issues/1075). I think it would be best if those were addressed in a separate PR (at the same time as adding Go 1.14 to the CI build matrix).

> Something that can also be done is to provide an appropriate error message when the build fails for a given version.

I think knowing that the fix works for all of the versions supported in CI (1.12 and 1.13) and the current newest version (Go 1.14) makes me tend towards thinking trying to add a special build time error message for Go 1.11 and older isn't worth the complexity/effort. Do you concur?

Let me know if there is anything else you'd like me to test!

**Comment by cpu** [comment]
> I thought that !go 1.13 and go 1.13 meant "less than Go 1.13" and "Go 1.13 and higher" but could be mistaken.

Re-reading the [Build Constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) docs made this clearer for me.

The `// +build go1.13` I added to the top of `helpers/derhelpers/derhelpers.go` in this branch will only be satisfied in Go version 1.13 onward (e.g. it is selected for Go 1.14 as well). From that it follows that the `// +build !go1.13` at the top of `helpers/derhelpers/derhelpers-legacy.go` will only be satisfied for versions < Go 1.13. I think that's exactly what we want in this scenario :+1:

**Comment by cpu** [comment]
Thanks!

**Comment by claucece** [comment]
Hi @cpu! 

You are right! Thanks so much for all the work!

**Pull request merged**
