### PR TITLE
Just building seems to do nothing

### PR DESCRIPTION
**Pull request by davidk-zenefits**

### CODE REVIEW

**Comment by andrewbuss** [comment]
This should probably be `go build ./cmd/...`

**Comment by lziest** [comment]
Please provide some context of this change since we don't consider "go build" is broken.

**Comment by andrewbuss** [comment]
`go build cmd/...` builds non-CFSSL packages like `cmd/cover` and `cmd/vet` rather than the intended `github.com/cloudflare/cfssl/cmd/...`

**Comment by jacobhaven** [comment]
I've [updated the BUILDING.md instructions](https://github.com/cloudflare/cfssl/commit/0ec15debaac95e372ef331c76d80e8aa4887ae8e) to use `go install` for the path `./cmd/...`, fixing the problem of matching the standard library `cmd` package.

**Pull request closed without merging**
