### PR TITLE
Move pkcs11key dependency to github.com/letsencrypt/pkcs11key and vendor

### PR DESCRIPTION
**Pull request by jacobhaven**
This addresses #519

### CODE REVIEW

**Comment by jacobhaven** [comment]
@jsha How would you suggest handling use of the `"github.com/cloudflare/cfssl/signer/pkcs11"` library? I.e. in [cli/config.go](https://github.com/cloudflare/cfssl/blob/jacob/vendor-pkcs11key/cli/config.go#L122). This is the last place that the `pkcs11` build tag is necessary.

**Comment by jsha** [comment]
I would suggest removing pkcs11 support from the cli; I'm not aware of anyone using it. Similarly in the RootFromConfig in that file.

**Comment by jsha** [comment]
I think we can also remove all of signer/pkcs11.

The pkcs11uri -> pkcs11key dependency is a little harder to break, and pkcs11uri isn't dependend upon by anythin else. We might want to break that into its own repo too?

**Comment by jacobhaven** [comment]
Alright, I'll go ahead and remove `signer/pkcs11`. Like you said, there's no dependency on `helpers/pkcs11uri`, so feel free to move that to `"github.com/letsencrypt/pkcs11key/uri"` (or leave it, it doesn't really matter)

**Comment by jacobhaven** [comment]
I'll remove the `helpers/pkcs11uri` package (and the vendored pkcs11key dependency) if https://github.com/letsencrypt/pkcs11key/pull/1 is merged.

**Comment by jsha** [comment]
Done.

**Comment by lziest** [comment]
lgtm

**Comment by kisom** [comment]
LGTM.

**Pull request merged**
