### PR TITLE
Add bundle option to /sign similar to /newcert

### PR DESCRIPTION
**Pull request by jacobhaven**
r? @kisom @lziest @fhossain

### CODE REVIEW

**Comment by jacobhaven** [comment]
I just did /sign and not /authsign as that's all we needed, but it would be trivial to copy the code if we want to have both.

**Comment by fhossain** [comment]
@jacobhaven I think we should do authsign for the sake of completeness :-)

**Comment by fhossain** [comment]
@jacobhaven I tested out the pull request branch and it fixes all the use cases I had with the second bundle call. All good from my end, Thanks.

**Comment by jacobhaven** [comment]
@kisom Yeah, it's odd that it was; it's in the `.gitignore`... \*fixed\*

**Comment by fhossain** [comment]
@kisom I think your changes were addressed. Is there some additional review changes outstanding with this pull request?

**Pull request merged**
