### PR TITLE
helpers/derhelpers: remove support for go1.12

### PR DESCRIPTION
**Pull request by thaJeztah**
go1.12 has reached EOL when go1.14 was released in 2020, so it should be safe to remove now.

Also removing uses of golang.org/x/crypto/ed25519, which is now part of stdlib:

    Beginning with Go 1.13, the functionality of this package was moved to the
    standard library as crypto/ed25519. This package only acts as a compatibility
    wrapper.

This partially reverts e45ead24ff2d3a16f9c662d6f3b787176096049e / 81e54732c78bc0320d4f6061b9d27b441d8ff8f7

### CODE REVIEW

**Comment by cpu** [comment]
> /cc @cpu PTAL hugs

Hi @thaJeztah - I don't have any maintainer permissions on this repository and haven't contributed to it since 2020. I recommend you tag @nickysemenza for this. Good luck!

**Comment by thaJeztah** [comment]
DOH! 🤦 My bad, I somehow looked at the "contributor", not review/maintainer to ping 😅 

(still feel free to review the change though! reviewing changes should reopen to anyone 🤗)

**Comment by nickysemenza** [comment]
thanks!

**Pull request merged**
