### PR TITLE
Support for extension in csr

### PR DESCRIPTION
**Pull request by orbli**
https://github.com/cloudflare/cfssl/issues/938

Below list a rough idea on how to implement. go fmt-ed so few other lines are changed (mainly inside struct)

### CODE REVIEW

**Comment by cbroglie** [comment]
Thanks @orbli! I've moved your changes over to #942, where we're going to make some additional changes and do some testing before merging to master.

**Comment by arulrajnet** [comment]
How can I use that `Extensions` in JSON

Here is my csr json

```
{
  "CN": "PLACEHOLDER",
  "key": {
    "algo": "ecdsa",
    "size": 521
  },
  "names": [
    {
      "C": "US",
      "O": "Example Inc"
    }
  ],
  "ca": {
    "expiry": "26280h"
  },
  "usages": [
    "signing",
    "key encipherment",
    "client auth",
    "server auth"
  ],
  "extensions": [
    {
      "Id": "2.5.29.17",
      "Value": "email:mail@domain.tld"
    }
  ]
}
```

Then

```
cfssl genkey -config signing-profiles.json csr.json | cfssljson -bare ca/inode
```
Error I am getting

```
json: cannot unmarshal string into Go struct field Extension.extensions.Id of type asn1.ObjectIdentifier
Failed to parse input: unexpected end of JSON input
```

Any help.?

**Comment by orbli** [comment]
@arulrajnet with my limited memory on the change i have done, I think you need the value to be base64 encoded in your csr json... it might be far too complex to support data types

**Comment by arulrajnet** [comment]
@orbli I understand it is too complex to support this kind of struct as JSON. As you suggested, I tried the following with values as base64.

### Extensions array itself base64

```
"extensions": "W3siSWQiOiAiMi41LjI5LjE3IiwiVmFsdWUiOiAiZW1haWw6bWFpbEBkb21haW4udGxkIn1dCg=="
```

This I am getting

```
json: cannot unmarshal string into Go struct field CertificateRequest.extensions of type []pkix.Extension
Failed to parse input: unexpected end of JSON input
```


### Extensions array element as base64

```
"extensions": [
  "eyJJZCI6ICIyLjUuMjkuMTciLCJWYWx1ZSI6ICJlbWFpbDptYWlsQGRvbWFpbi50bGQifQo="
]
```

This I am getting

```
json: cannot unmarshal string into Go struct field CertificateRequest.extensions of type pkix.Extension
Failed to parse input: unexpected end of JSON input
```

### Extensions array element value as base64

```
"extensions": [
  {
    "Id": "Mi41LjI5LjE3Cg==",
    "Value": "ZW1haWw6bWFpbEBkb21haW4udGxkCg=="
  }
]
```

This I am getting 

```
json: cannot unmarshal string into Go struct field Extension.extensions.Id of type asn1.ObjectIdentifier
Failed to parse input: unexpected end of JSON input
```

Is there anything I am missing?

**Comment by orbli** [comment]
Indeed I think u should try"extensions": [  {    "Id": "2.5.29.17",    "Value": "ZW1haWw6bWFpbEBkb21haW4udGxkCg=="  }] On 8 May 2020 13:07, Arul <notifications@github.com> wrote:
@orbli I understand it is too complex to support this kind of struct as JSON. As you suggested, I tried the following with values as base64.
Extensions array itself base64
"extensions": "W3siSWQiOiAiMi41LjI5LjE3IiwiVmFsdWUiOiAiZW1haWw6bWFpbEBkb21haW4udGxkIn1dCg=="

This I am getting
json: cannot unmarshal string into Go struct field CertificateRequest.extensions of type []pkix.Extension
Failed to parse input: unexpected end of JSON input

Extensions array element as base64
"extensions": [
  "eyJJZCI6ICIyLjUuMjkuMTciLCJWYWx1ZSI6ICJlbWFpbDptYWlsQGRvbWFpbi50bGQifQo="
]

This I am getting
json: cannot unmarshal string into Go struct field CertificateRequest.extensions of type pkix.Extension
Failed to parse input: unexpected end of JSON input

Extensions array element value as base64
"extensions": [
  {
    "Id": "Mi41LjI5LjE3Cg==",
    "Value": "ZW1haWw6bWFpbEBkb21haW4udGxkCg=="
  }
]

This I am getting
json: cannot unmarshal string into Go struct field Extension.extensions.Id of type asn1.ObjectIdentifier
Failed to parse input: unexpected end of JSON input

Is there anything I am missing?

**Comment by arulrajnet** [comment]
@orbli That is also not working. Same error.

**Comment by orbli** [comment]
Maybe you can try "Id": ["2", "5", "29", "17"]  or without being string. I don't hv the program in hand so I can't confirm answers myself

**Comment by arulrajnet** [comment]
```
  "extensions": [
    {
      "Id":  [2, 5, 29, 17],
      "Value": "ZW1haWw6bWFpbEBkb21haW4udGxkCg=="
    }
  ]
```
This works. 

Thanks @orbli

**Comment by arulrajnet** [comment]
@cbroglie We need better documentation for this.

**Pull request merged**
