### PR TITLE
Add support for bundling certs with Client Auth Key Usage

### LINKED ISSUE #588: API bundle endpoint can't be used for bundling client certificates
The key usages used for verification within the bundler package seem to be hardcoded to a limited subset of those possible, which doesn't include `clientAuth`: https://github.com/cloudflare/cfssl/blob/92f037e39eb103fb30f9151be40d9ed267fc4ae2/bundler/bundler.go#L158

### PR DESCRIPTION
**Pull request by jacobhaven**
Should fix #588 and #608

r? @kisom @lziest @grittygrease

### CODE REVIEW

**Comment by lziest** [comment]
add a specific test on this?

**Comment by jacobhaven** [comment]
@lziest My main concern is that it requires generating Root, Intermediate and Client Auth Leaf Certificates and the tests will fail when they expire.

**Comment by lziest** [comment]
I would write a script using cfssl to automate that, then we don't need to worry too much.

**Comment by jacobhaven** [comment]
@lziest *Test certs along with script to generate them added*

**Comment by lziest** [comment]
lgtm

**Pull request merged**
