### PR TITLE
refactor cmd/multirootca/config to rootconfig

### PR DESCRIPTION
**Pull request by lziest**
- Export RawMap type from rootconfig
- Export LoadRoot function from rootconfig
- Enable selective parsing of a root

### CODE REVIEW

**Comment by grittygrease** [comment]
Is "rootconfig" the right name?

**Comment by lziest** [comment]
I need suggestions

**Comment by grittygrease** [comment]
@kisom what do you think this package should be called?

**Comment by kisom** [comment]
@lziest @grittygrease since this is concerned with the configuration of labels, it might make sense to name it something like `labelconfig`.

**Comment by grittygrease** [comment]
How about a "multiroot" package with a "config" sub-package.

**Comment by kisom** [comment]
I like that idea.

**Comment by lziest** [comment]
+1

**Comment by grittygrease** [comment]
LGTM

**Comment by kisom** [comment]
LGTM.

**Pull request merged**
