### PR TITLE
run gofmt -w -s

### PR DESCRIPTION
**Pull request by jfrazelle**
little things drive me nuts :innocent:

### CODE REVIEW

**Comment by jfrazelle** [comment]
added a check in test.sh, so this can be caught by CI in future

**Comment by kisom** [comment]
LGTM.

**Comment by lziest** [comment]
LGTM, and I introduced many of those I am afraid. :-P

**Comment by jfrazelle** [comment]
https://github.com/jayphelps/git-blame-someone-else :P

On Thu, Feb 11, 2016 at 5:04 PM, Zi Lin <notifications@github.com> wrote:

> LGTM, and I introduced many of those I am afraid. :-P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudflare/cfssl/pull/510#issuecomment-183137003>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jacobhaven** [comment]
<3

**Pull request merged**
