### PR TITLE
CertInfo CLI and API endpoint returning info about local or remote X.509 certs

### PR DESCRIPTION
**Pull request by jacobhaven**

### CODE REVIEW

**Comment by jacobhaven** [comment]
"data" might also not be the best name. Maybe "text", "certdata", "certinfo"?

**Comment by kisom** [comment]
"certinfo" seems the most appropriate.

**Comment by grittygrease** [comment]
@jacobhaven can you update this with "certinfo"?

**Comment by jacobhaven** [comment]
Updated a few things, and added API endpoint.

**Comment by lziest** [comment]
rebasing on top of the current master should fix the build. There was a test on a expired certificate and I fixed it.

**Comment by jacobhaven** [comment]
@lziest Cool. After rebasing all the tests pass

**Comment by grittygrease** [comment]
LGTM

**Pull request merged**
