### PR TITLE
Zi/sign pathlen

### PR DESCRIPTION
**Pull request by lziest**
A new CA config entry: CAContraint, which can be used to specify intermediate CA's pathlen constraints.

### CODE REVIEW

**Comment by kisom** [comment]
LGTM, but the docs will need to be updated for this, too.

**Comment by lziest** [comment]
good point. I will go through the doc.

**Comment by lziest** [comment]
turns out the cli tester caught some bugs I put some fixes in.

**Comment by lziest** [comment]
@kisom check ffe30b3 for my doc update.

**Comment by kisom** [comment]
LGTM.

**Pull request merged**
