### PR TITLE
codecoverage

### PR DESCRIPTION
**Pull request by codyli520**
Gradually adding unit tests

### CODE REVIEW

**Comment by grittygrease** [comment]
What's your plan for this PR?

**Comment by codyli520** [comment]
mainly working on the code coverage for api and cli packages, try to get api code coverage pass 80% mark (currently 55%)  and cli code coverage pass 50% mark (currently 25%)

**Comment by grittygrease** [comment]
Rather than one large pull request, consider splitting this out into smaller, more focused branches.

**Comment by codyli520** [comment]
ok, will close this PR soon and create new ones

**Pull request closed without merging**
