### PR TITLE
Add support for generic KeyRequests (e.g. specifying custom x509.SignatureAlgorithms)

### PR DESCRIPTION
**Pull request by jacobhaven**

### CODE REVIEW

**Comment by lziest** [comment]
consider fix the sad failing test?

**Comment by jacobhaven** [comment]
This is blocked on a json Unmarshaling error

**Comment by jacobhaven** [comment]
Unblocked now. Note that when unmarshalling into a CSR, the KeyRequest interface field must be initialized to a concrete type (e.g. by using `csr.NewBasicKeyRequest()`)

**Comment by jacobhaven** [comment]
Fields renames to `KeyRequest.A` and `KeyRequest.S`. They only really need to be used to avoid a go vet [unkeyed composite literals warning](https://godoc.org/golang.org/x/tools/cmd/vet#hdr-Unkeyed_composite_literals), like in [testing_helpers_test](https://github.com/cloudflare/cfssl/pull/315/files#diff-fb9516439dedb9fd94c8a84b928666cfR30)

**Comment by lziest** [comment]
LGTM

**Pull request merged**
