### PR TITLE
CAConstraint replacing the CA bool flag for more CA signing control

### PR DESCRIPTION
**Pull request by lziest**
Experimental PR on how to sign a CA certificate with customizable pathlen

### CODE REVIEW

**Comment by lziest** [comment]
@fhossain probably going to solve your immediate need
@tam7t I think I need to rebase on your extension work eventually. So this is on hold.

**Comment by fhossain** [comment]
@lziest - thanks. This change does address my requirement.

**Comment by lziest** [comment]
rebased. hopefully tests pass.

**Comment by lziest** [comment]
need more plumbing

**Comment by lziest** [comment]
close this, will create a new PR.

**Pull request closed without merging**
