### PR TITLE
Fixes a few bugs

### PR DESCRIPTION
**Pull request by ekristen**
@kisom this fixes a few bugs where the binaries weren't being populated correctly. Also updated the BUILDING.md documentation.

### CODE REVIEW

**Comment by kisom** [comment]
@ekristen Would it be possible to put the built binaries in their own directory? I think that would make cleaning a lot easier.

**Comment by ekristen** [comment]
Like a `dist` directory?

**Comment by kisom** [comment]
Perfect.

**Comment by ekristen** [comment]
@kisom it'll build to the `dist/` folder now

**Comment by kisom** [comment]
@ekristen Thanks!

**Comment by ekristen** [comment]
Anytime, glad to help where I can!

**Pull request merged**
