### PR TITLE
certdb/dbconf package should not touch specific db drivers

### PR DESCRIPTION
**Pull request by lziest**
Trying to address #545 @jacobhaven can you verify that work? I have tested locally and it seemed to work.

### CODE REVIEW

**Comment by lziest** [comment]
OK, need to fix tests

**Comment by lziest** [comment]
OK I think the PR is ready.

**Comment by kisom** [comment]
LGTM.

**Comment by lziest** [comment]
verified that it solves #545 since we get rid of sqlite support in cfssl binaries, sqlite is only used for testing.

**Pull request merged**
