### PR TITLE
update certificate-transparency-go, protobuf and mattn/go-sqlite3

### PR DESCRIPTION
**Pull request by laverya**
This fixes compilation errors on go 1.11+ and GOOS=windows

[replicatedhq/ship](https://github.com/replicatedhq/ship) imports this, and our goreleaser build failed after updating to go 1.12. Overriding the dependency in Gopkg.toml works https://github.com/replicatedhq/ship/pull/892/commits/faffe1c30141f613df1d25cd313d94fb2814eeee, but presumably we will not be the only project to encounter this issue.

### CODE REVIEW

**Comment by laverya** [comment]
The Go 1.10 build failed, but considering that that build [fails on master too](https://travis-ci.org/laverya/cfssl/builds/512613208) I'm calling "not my fault"

**Comment by cbroglie** [comment]
Thanks @laverya. Can you update #984 to drop support for Go 1.10 as well? Then we can merge that first, and then rebase this one and confirm all is passing before merging.

**Comment by laverya** [comment]
Will do!

**Comment by laverya** [comment]
@cbroglie tests all pass after dropping Go 1.10

**Pull request merged**
