### PR TITLE
Adds a basic healthz endpoint

### PR DESCRIPTION
**Pull request by cmattoon**
Addresses #834 by adding a basic health check

    $ curl -s http://localhost:8888/api/v1/cfssl/healthz
    {"success":true,"result":{"healthy":true},"errors":[],"messages":[]}

### CODE REVIEW

**Comment by cbroglie** [comment]
@cmattoon Why are you calling it `healthz`, and not simply `health`?

**Comment by cbroglie** [comment]
Thanks for the link, that's good to know. I'd like to stick with `/health` for this project - do you mind making that change? Happy to merge after that, thanks.

**Comment by cmattoon** [comment]
Fixed!

**Comment by cbroglie** [comment]
Thanks again, @cmattoon!

**Pull request merged**
