### PR TITLE
Update github.com/google/certificate-transparency/go

### PR DESCRIPTION
**Pull request by rolandshoemaker**
Updates `github.com/google/certificate-transparency/go` to current `master`.

### CODE REVIEW

**Comment by rolandshoemaker** [comment]
Ping. This is a blocker for updating the `letsencrypt/boulder` vendored `github.com/cloudflare/cfssl` and `github.com/google/certificate-transparency` dependencies.

Test failures seem to be unrelated to these changes.

**Comment by lziest** [comment]
it's quite big PR, I certainly hope to make CI green. I can try to fix it on master, and can you try rebase on top of the fix later?

**Comment by kisom** [comment]
OS X travis failure is a known issue, otherwise tests pass. I'll review this PR today.

**Comment by kisom** [comment]
I don't think `certdb/testdb/certstore_development.db` was supposed to change --- it's in [`.gitignore`](https://github.com/cloudflare/cfssl/blob/master/.gitignore).

**Pull request merged**
