### PR TITLE
add gencsr command

### PR DESCRIPTION
**Pull request by lziest**

### CODE REVIEW

**Comment by nixwizard** [comment]
Is gencsr api endpoint going to be implemented?

**Comment by lziest** [comment]
@nixwizard I would like to know about the use case. To me, supplying a private key and getting back a CSR from a service doesn't make much sense.

**Comment by nixwizard** [comment]
Very simple process. We have an external CA provider. A private
      key and CSR is generated on our side and then we transfer the CSR
      to the provider to get back a certificate.
    
    
    On 11.05.2017 20:32, Zi Lin wrote:
    
    
      @nixwizard I would like to know
        about the use case. To me, supplying a private key and getting
        back a CSR from a service doesn't make much sense.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cloudflare/cfssl","title":"cloudflare/cfssl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cloudflare/cfssl"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lziest in #764: @nixwizard I would like to know about the use case. To me, supplying a private key and getting back a CSR from a service doesn't make much sense."}],"action":{"name":"View Pull Request","url":"https://github.com/cloudflare/cfssl/pull/764#issuecomment-300861234"}}}

**Comment by lziest** [comment]
then we have api genkey, which should satisfy your needs.

**Pull request merged**
